In [1]:
from matplotlib import pyplot as plt
from PIL import Image
import numpy as np
import pytesseract
import cv2
import os 
import keras
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
import os

In [44]:
def OCR_scan(img_path = '', pre = 'thresh', save_path = '', number_pics = ''):
    image = cv2.imread(img_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    if pre == 'thresh':
        ret, gray = cv2.threshold(gray, 0, 255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    elif pre =='blur':
        gray = cv2.medianBlur(gray, 3)
    save_into = save_path+number_pics+'.jpg'
    cv2.imwrite(save_into, gray) 

In [45]:
img_list = 'crop_image\\'
pre1 = 'thresh'
pre2 = 'blur'
save_path1 = 'preprocess_thresh\\'
save_path2 = 'preprocess_blur\\'
count = '1'
count_str = 1
for i in os.listdir(img_list):
    img_path = img_list+i
    OCR_scan(img_path = img_path, pre = pre1, save_path = save_path1, number_pics = count)
    OCR_scan(img_path = img_path, pre = pre2, save_path = save_path2, number_pics = count)
    count_str += 1
    count = str(count_str)

In [37]:
filename = 'preprocess_thresh\\'
list_thresh = []
list_blur = []
list_o = []
list_test = []
for i in range(28):
    name = i+1
    thresh = filename + str(name) + '.jpg'
    blur = 'preprocess_blur\\'+ str(name) + '.jpg'
    original = 'crop_image\\'+ str(name) + '.jpg'
    test = 'preprocess_test\\'+ str(name) + '.jpg'
    list_thresh.append(pytesseract.image_to_string(Image.open(thresh)))
    list_blur.append(pytesseract.image_to_string(Image.open(blur)))
    list_o.append(pytesseract.image_to_string(Image.open(original)))
    list_test.append(pytesseract.image_to_string(Image.open(test)))

# print(list)

In [20]:
for i in list_thresh:
    print('#{}'.format(i))

#J 59 PA j
664.80
#62 HS
7108
#
#
#1
99.97
#
#ead
043.09
#
#BY 59-41
so7 00
#59-81
385.59
#54-H}
6982
#
#59°51
09841
#81-61
135.56
#60-F1
506.70
#Be "1
0200
#16M
06.
#
#S5-Po i
2840
#
#
#
#
#
#
#136.29
#
#59-(2
316.61


In [21]:
for i in list_blur:
    print('#{}'.format(i))

#
#
#
#
#59897
#B 99°C2
012.08
#ie
043.09
#
#
#
#
#
#39-51
098.41
#81-61
135.56
#60:F1
506.70
#
#1
0

6-H
61

i
#
#Gar) ¢
7840)
#
#
#
#
#
#
#136.29
#70-01
/39 16
#39-(2
316.01


In [23]:
for i in list_o:
    print('#{}'.format(i))

#, 59-P1 '
664.80
#
#
#
#
#
#136.29
#
#59-(7
316.01
#
#
#
#U1]
98.97
#
#78-G)
043.08)
#59-E]
708.50
#
#
#36-HT
4882
#am 59-51
098.41)
#81-61
1135.56
#60-F1
506.70
#63-/
0200
#
#
#55-79
7840)
#
#


In [73]:
img_path = 'crop_image\\1.jpg'
image = cv2.imread(img_path,0)
# plt.imshow(image, cmap = 'gray')
# hist,bins = np.histogram(image.flatten(),256,[0,255]) 
# plt.imshow(hist,cmap = 'gray')
img = cv2.equalizeHist(image)
ret, img = cv2.threshold(img, 180, 255,cv2.THRESH_BINARY)

kernel = np.ones((3,3),np.uint8)
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
# ret, gray = cv2.threshold(closing, 180, 255,cv2.THRESH_BINARY)
test = Image.fromarray(closing.astype('uint8'), 'gray')
text = pytesseract.image_to_string(Image.open(closing))
print(text)
plt.imshow(closing, cmap = 'gray')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


ValueError: unrecognized image mode

In [43]:
img_list = 'crop_image\\'
# img = cv2.imread(img_path,0)
# ret, gray = cv2.threshold(img, 150, 255,cv2.THRESH_BINARY)
# plt.imshow(gray, cmap = 'gray')
def OCR_test(img_path = '', pre = 'thresh', save_path = '', number_pics = ''):
    image = cv2.imread(img_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    if pre == 'thresh':
        ret, gray = cv2.threshold(gray, 180, 255,cv2.THRESH_BINARY)
#     elif pre =='blur':
#         gray = cv2.medianBlur(gray, 3)
    save_into = save_path+number_pics+'.jpg'
    cv2.imwrite(save_into, gray) 
count = '1'
count_str = 1
for i in os.listdir(img_list):
    img_path = img_list+i
    OCR_test(img_path = img_path, pre = 'thresh', save_path = 'preprocess_test\\', number_pics = count)
    count_str += 1
    count = str(count_str)

In [44]:
list_test = []
for i in range(28):
    name = i+1
    test = 'preprocess_test\\'+ str(name) + '.jpg'
    list_test.append(pytesseract.image_to_string(Image.open(test)))
for i in list_test:
    print('#{}'.format(i))

#59-P1
661.80
#
#FT,
170.78
#
#59-1
98.97]
#
#
#
#
#59-B1 |
38559
#50H
6882 fi
#
#9-51 |
098.41]
#
#§0-F
506.70)
#63-41]
02004
#
#
#
#
#
#ae “TT
#
#
#
#59-ul
136.29
#1-C1
789.15
#


In [2]:
'''
#Train a simple deep CNN on the CIFAR10 small images dataset.

It gets to 75% validation accuracy in 25 epochs, and 79% after 50 epochs.
(it's still underfitting at that point, though).
'''

from __future__ import print_function
import keras
from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
import os

batch_size = 32
num_classes = 10
epochs = 100
data_augmentation = True
num_predictions = 20
save_dir = os.path.join(os.getcwd(), 'saved_models')
model_name = 'keras_cifar10_trained_model.h5'

# The data, split between train and test sets:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# Convert class vectors to binary class matrices.
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=x_train.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

# initiate RMSprop optimizer
opt = keras.optimizers.rmsprop(lr=0.0001, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(x_train, y_train,
              batch_size=batch_size,
              epochs=epochs,
              validation_data=(x_test, y_test),
              shuffle=True)
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        zca_epsilon=1e-06,  # epsilon for ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        # randomly shift images horizontally (fraction of total width)
        width_shift_range=0.1,
        # randomly shift images vertically (fraction of total height)
        height_shift_range=0.1,
        shear_range=0.,  # set range for random shear
        zoom_range=0.,  # set range for random zoom
        channel_shift_range=0.,  # set range for random channel shifts
        # set mode for filling points outside the input boundaries
        fill_mode='nearest',
        cval=0.,  # value used for fill_mode = "constant"
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False,  # randomly flip images
        # set rescaling factor (applied before any other transformation)
        rescale=None,
        # set function that will be applied on each input
        preprocessing_function=None,
        # image data format, either "channels_first" or "channels_last"
        data_format=None,
        # fraction of images reserved for validation (strictly between 0 and 1)
        validation_split=0.0)

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_train, y_train,
                                     batch_size=batch_size),
                        epochs=epochs,
                        validation_data=(x_test, y_test),
                        workers=4)

# Save model and weights
if not os.path.isdir(save_dir):
    os.makedirs(save_dir)
model_path = os.path.join(save_dir, model_name)
model.save(model_path)
print('Saved trained model at %s ' % model_path)

# Score trained model.
scores = model.evaluate(x_test, y_test, verbose=1)
print('Test loss:', scores[0])
print('Test accuracy:', scores[1])

x_train shape: (50000, 32, 32, 3)
50000 train samples
10000 test samples
Using real-time data augmentation.


ValueError: `steps_per_epoch=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `steps_per_epoch` or use the `keras.utils.Sequence` class.

In [3]:


from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

batch_size = 128
num_classes = 10
epochs = 20

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

60000 train samples
10000 test samples
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 512)               401920    
_________________________________________________________________
dropout_6 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_7 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________
Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [=======================

In [35]:
from PIL import Image
from matplotlib import pyplot as plt
img = Image.open('five.jpg')
# print(np.array(img).shape)
image = img.resize((28,28), Image.LANCZOS)
image = np.array(image)
image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [44]:
import cv2
import numpy as np 

img = np.reshape(image, (1,28*28))
a = model.predict(img)
ind = a.tolist()[0]
print(ind.index(1))


5


# Image Preprocessing