In [1]:
from matplotlib import pyplot as plt
from PIL import Image
import numpy as np
import pytesseract
import cv2
import os 


In [44]:
def OCR_scan(img_path = '', pre = 'thresh', save_path = '', number_pics = ''):
    image = cv2.imread(img_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    if pre == 'thresh':
        ret, gray = cv2.threshold(gray, 0, 255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)
    elif pre =='blur':
        gray = cv2.medianBlur(gray, 3)
    save_into = save_path+number_pics+'.jpg'
    cv2.imwrite(save_into, gray) 

In [45]:
img_list = 'crop_image\\'
pre1 = 'thresh'
pre2 = 'blur'
save_path1 = 'preprocess_thresh\\'
save_path2 = 'preprocess_blur\\'
count = '1'
count_str = 1
for i in os.listdir(img_list):
    img_path = img_list+i
    OCR_scan(img_path = img_path, pre = pre1, save_path = save_path1, number_pics = count)
    OCR_scan(img_path = img_path, pre = pre2, save_path = save_path2, number_pics = count)
    count_str += 1
    count = str(count_str)

In [37]:
filename = 'preprocess_thresh\\'
list_thresh = []
list_blur = []
list_o = []
list_test = []
for i in range(28):
    name = i+1
    thresh = filename + str(name) + '.jpg'
    blur = 'preprocess_blur\\'+ str(name) + '.jpg'
    original = 'crop_image\\'+ str(name) + '.jpg'
    test = 'preprocess_test\\'+ str(name) + '.jpg'
    list_thresh.append(pytesseract.image_to_string(Image.open(thresh)))
    list_blur.append(pytesseract.image_to_string(Image.open(blur)))
    list_o.append(pytesseract.image_to_string(Image.open(original)))
    list_test.append(pytesseract.image_to_string(Image.open(test)))

# print(list)

In [20]:
for i in list_thresh:
    print('#{}'.format(i))

#J 59 PA j
664.80
#62 HS
7108
#
#
#1
99.97
#
#ead
043.09
#
#BY 59-41
so7 00
#59-81
385.59
#54-H}
6982
#
#59°51
09841
#81-61
135.56
#60-F1
506.70
#Be "1
0200
#16M
06.
#
#S5-Po i
2840
#
#
#
#
#
#
#136.29
#
#59-(2
316.61


In [21]:
for i in list_blur:
    print('#{}'.format(i))

#
#
#
#
#59897
#B 99°C2
012.08
#ie
043.09
#
#
#
#
#
#39-51
098.41
#81-61
135.56
#60:F1
506.70
#
#1
0

6-H
61

i
#
#Gar) ¢
7840)
#
#
#
#
#
#
#136.29
#70-01
/39 16
#39-(2
316.01


In [23]:
for i in list_o:
    print('#{}'.format(i))

#, 59-P1 '
664.80
#
#
#
#
#
#136.29
#
#59-(7
316.01
#
#
#
#U1]
98.97
#
#78-G)
043.08)
#59-E]
708.50
#
#
#36-HT
4882
#am 59-51
098.41)
#81-61
1135.56
#60-F1
506.70
#63-/
0200
#
#
#55-79
7840)
#
#


In [73]:
img_path = 'crop_image\\1.jpg'
image = cv2.imread(img_path,0)
# plt.imshow(image, cmap = 'gray')
# hist,bins = np.histogram(image.flatten(),256,[0,255]) 
# plt.imshow(hist,cmap = 'gray')
img = cv2.equalizeHist(image)
ret, img = cv2.threshold(img, 180, 255,cv2.THRESH_BINARY)

kernel = np.ones((3,3),np.uint8)
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
# ret, gray = cv2.threshold(closing, 180, 255,cv2.THRESH_BINARY)
test = Image.fromarray(closing.astype('uint8'), 'gray')
text = pytesseract.image_to_string(Image.open(closing))
print(text)
plt.imshow(closing, cmap = 'gray')

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


ValueError: unrecognized image mode

In [43]:
img_list = 'crop_image\\'
# img = cv2.imread(img_path,0)
# ret, gray = cv2.threshold(img, 150, 255,cv2.THRESH_BINARY)
# plt.imshow(gray, cmap = 'gray')
def OCR_test(img_path = '', pre = 'thresh', save_path = '', number_pics = ''):
    image = cv2.imread(img_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    if pre == 'thresh':
        ret, gray = cv2.threshold(gray, 180, 255,cv2.THRESH_BINARY)
#     elif pre =='blur':
#         gray = cv2.medianBlur(gray, 3)
    save_into = save_path+number_pics+'.jpg'
    cv2.imwrite(save_into, gray) 
count = '1'
count_str = 1
for i in os.listdir(img_list):
    img_path = img_list+i
    OCR_test(img_path = img_path, pre = 'thresh', save_path = 'preprocess_test\\', number_pics = count)
    count_str += 1
    count = str(count_str)

In [44]:
list_test = []
for i in range(28):
    name = i+1
    test = 'preprocess_test\\'+ str(name) + '.jpg'
    list_test.append(pytesseract.image_to_string(Image.open(test)))
for i in list_test:
    print('#{}'.format(i))

#59-P1
661.80
#
#FT,
170.78
#
#59-1
98.97]
#
#
#
#
#59-B1 |
38559
#50H
6882 fi
#
#9-51 |
098.41]
#
#§0-F
506.70)
#63-41]
02004
#
#
#
#
#
#ae “TT
#
#
#
#59-ul
136.29
#1-C1
789.15
#
